#!/usr/bin/env python

import sys
from os import path
from src.main import oerp2odoo
from src.util import load_replacements

if (len(sys.argv) < 2):
    print("\nHelper for converting an OpenERP (v7) module for use with Odoo 12+")
    print("Usage: oerp2odoo <module_path> [custom_replacements_file]\n")
else:
    mod_path = path.abspath(sys.argv[1])

    replacements = None
    if len(sys.argv) > 2:
        replacements_file = sys.argv[2]
        replacements = load_replacements(path.abspath(replacements_file))

    oerp2odoo(mod_path, replacements)
